import json
deep = json.load(open('/home/rory/Projects/news-pwa/deepdives.json'))
TODAY = "2026-09-22"

dd = {
"us-10y-497-fed-speeches-2026-09-22": {
 "headline":"US 10-year yield hovers near 4.97% as traders bet on another Fed hike",
 "summary":"The 10-year Treasury slipped about 3bp to 4.97% on Monday as traders priced another 25bp hike this year and awaited a week of Fed speeches.",
 "detail":"The benchmark 10-year US Treasury note eased to around 4.97% on Monday, down about 3 basis points on the session, after last week's repricing put long-end yields near their highest since before the 2008 financial crisis. TradingEconomics noted the small pullback came as investors awaited several appearances by Federal Reserve officials through the week for further clues on the monetary path.\n\nThe market's central assumption is that the Fed is not finished. Traders currently expect the central bank to deliver another 25-basis-point rate hike before the end of the year, on top of the September increase. Fed Chair Kevin Warsh has stressed inflation risks in the wake of the hot August core CPI reading and the energy shock from the Iran war, and short-term yields have moved higher accordingly.\n\nFor borrowers the message is the same one that has dominated bond markets for weeks: elevated long-term costs are proving persistent. The entire curve, from short maturities to the 30-year, has backed up as investors demand more compensation for sticky inflation, record debt issuance and an energy-driven price scare. Whether this week's Fed speakers reinforce or soften that repricing will shape the direction of long yields into October.",
 "sources":["TradingEconomics","CNBC"],"source_urls":["https://tradingeconomics.com/united-states/government-bond-yield","https://www.cnbc.com/quotes/US10Y"],"updated":TODAY
},
"australia-ai-human-control-2026-09-22": {
 "headline":"Albanese joins 22 world leaders demanding AI stay 'under human control'",
 "summary":"Anthony Albanese is among 22 signatories warning that AI development 'could outpace our ability to manage emerging risks', urging guardrails ahead of the UN General Assembly.",
 "detail":"Anthony Albanese was among 22 national leaders to sign a joint statement on the eve of the United Nations General Assembly in New York warning that the pace of AI development 'could outpace our ability to manage emerging risks'. Australia's ABC reported the signatories are urgently calling for global guardrails to keep AI 'under human control', arguing existing efforts to ring-fence the technology are failing.\n\nThe demands go beyond rhetoric. The statement calls for mandatory pre-deployment testing of frontier AI models, independent evaluation, transparent safety protocols and globally consistent standards, including the creation of a UN-style international organisation to set standards and oversee AI use. The AFR reported Australia joined 19 other nations plus the European Commission in the push.\n\nThe intervention is a deliberate play by medium-sized powers to shape the rules of a technology where the US and China are competing for dominance. Albanese is using the moment to burnish Australia's credentials as it campaigns for a two-year term on the UN Security Council, and he met EU leaders in New York beforehand. It also sets Australia at odds with a White House that has vowed to fight AI regulation, framing the coming global debate over who governs frontier AI.",
 "sources":["ABC News","AFR"],"source_urls":["https://newsapp.abc.net.au/news/2026-09-22/australia-joins-global-push-for-ai-controls/107179312","https://www.afr.com/politics/federal/australia-joins-21-nation-push-to-ensure-humans-control-ai-20260922-p60zb5"],"updated":TODAY
},
"sydney-smartglasses-pool-ban-2026-09-22": {
 "headline":"City of Sydney bans smart glasses from pools",
 "summary":"The City of Sydney joined Canterbury-Bankstown, Brisbane and Yarra in banning AI smart glasses at aquatic centres, raising pressure for national rules.",
 "detail":"The City of Sydney on Monday became the latest local government to ban smart glasses from its swimming pools and aquatic centres, joining Canterbury-Bankstown, Brisbane and Melbourne's Yarra in the crackdown. Nine reported the move came amid growing pressure on the federal government to bring in national restrictions, with councils framing the devices as a privacy threat due to their ability to record people covertly.\n\nUnder the new rules, lifeguards will be able to confiscate the AI-equipped glasses and evict users who refuse to comply. Canterbury-Bankstown, the first Sydney council to introduce a blanket ban of the sort (reported by the ABC on September 18), moved to 'protect families and kids' from the technology, and the City of Sydney's addition follows the same logic.\n\nThe local bans are running well ahead of federal policy. As smart glasses with camera and recording capability reach consumers, councils are opting for precautionary limits while the federal government weighs whether national rules are warranted. The clustering of bans across New South Wales, Queensland and Victoria signals this is becoming a coordinated movement rather than isolated local decisions, and the pressure is now squarely on Canberra to set a consistent national standard.",
 "sources":["Nine","ABC News"],"source_urls":["https://www.nine.com.au/australia-news/nsw/pressure-on-federal-government-grows-as-another-council-bans-pervert-glasses-20260922-p60zbh.html","https://www.abc.net.au/news/2026-09-18/nsw-canterbury-bankstown-council-ai-glasses-ban-sydney/106841918"],"updated":TODAY
},
"germany-state-elections-final-2026-09-22": {
 "headline":"CDU suffers historic German state-election defeat as AfD tops Mecklenburg-Vorpommern",
 "summary":"Merz's CDU missed the 5% threshold in Mecklenburg-Vorpommern for the first time ever, the AfD led with 38%, and the Left won Berlin.",
 "detail":"Germany's final state elections of the year delivered a sharp political shake-up and a historic humiliation for Chancellor Friedrich Merz's CDU. In Mecklenburg-Western Pomerania, the CDU missed the 5% threshold for parliamentary representation for the first time in its postwar history, recording its worst-ever result in the state at just 4.9%. The far-right Alternative for Germany (AfD) came first with about 38%, nearly double its 2021 share, and was closely followed by the SPD's 35.5%, with incumbent premier Manuela Schwesig likely staying on in a left-of-centre coalition.\n\nIn Berlin, the socialist Left Party triumphed with roughly 26% of the vote, doubling its share, while the CDU, which had led the state government, collapsed to around 19-20%. The AfD became Berlin's third-largest party at about 16%. The CDU's previous governing coalition with the SPD lost its majority, and a Left-SPD-Greens arrangement now looks the most plausible path to government in the capital.\n\nMerz called the Mecklenburg result 'a disaster' and 'nothing to sugar-coat', but vowed to press on, his third electoral defeat in two weeks after a heavy loss in Saxony-Anhalt on September 6. The results, which come despite nationwide polls showing the coalition losing its majority, intensify pressure on the chancellor from within his own party and coalition. They also signal a widening of support toward both political extremes, with the AfD declaring its containment strategy has failed and the Left leveraging its Berlin win as a springboard ahead of the federal campaign.",
 "sources":["Reuters","DW","Euronews","The Guardian"],"source_urls":["https://www.reuters.com/world/merz-clings-after-german-election-disaster-2026-09-21/","https://www.dw.com/en/german-state-elections-deal-a-blow-to-chancellor-friedrich-merz/a-79348585","https://www.euronews.com/my-europe/2026/09/21/germany-the-left-triumphs-in-berlin-as-afd-surges-in-mecklenburg-western-pomerania"],"updated":TODAY
},
"eu-datacentre-sustainability-rules-2026-09-22": {
 "headline":"EU unveils data-centre sustainability rules",
 "summary":"The European Commission proposed rules to monitor energy and water use at data centres, with binding minimum standards only from 2027.",
 "detail":"The European Commission has unveiled new sustainability rules aimed at monitoring the water and energy consumption of energy-hungry data centres, Euronews reported. The proposal responds to the explosive growth of cloud and AI computing infrastructure, which is becoming a major consumer of electricity and water across the bloc.\n\nUnder the plan, operators would be required to report on their energy and water use, giving regulators and the public visibility into an environmental footprint that has grown rapidly with the AI boom. Binding minimum performance rules would only be introduced in 2027, meaning the near-term compliance burden is disclosure rather than hard standards.\n\nThe move sits within a broader European push to reduce the environmental cost of digital infrastructure while simultaneously building out domestic computing capacity. European Central Bank President Christine Lagarde has argued Europe must construct far more data centres to preserve its AI autonomy and capture productivity gains. The EU wants the AI-driven computing build-out, but it also wants that build-out to be sustainable, and the new rules are an early attempt to reconcile the two.",
 "sources":["Euronews"],"source_urls":["https://www.euronews.com/"],"updated":TODAY
},
"xai-grok-4-7-launch-2026-09-22": {
 "headline":"xAI finally ships Grok 4.7, big but still second place",
 "summary":"After five delays since July, xAI released Grok 4.7 (2.1T params) on Monday; benchmarks still put it behind Claude Fable 5.1.",
 "detail":"Elon Musk's xAI released Grok 4.7 on Monday, delivering its best model to date after a string of public delays. Musk had walked back the timeline at least five times since late July, going from 'four weeks out' to '10 days' to 'needs a few more days to cook' on September 11, before the model went live with no waitlist in the Grok app, Cursor, Grok Build and the xAI API.\n\nThe model packs 2.1 trillion parameters, up 40% from Grok 4.6's 1.5 trillion, with supplemental training on SpaceX engineering data. It is priced at $2 per million input tokens and $6 per million output tokens, the same price point as its predecessor. Decrypt reported xAI describing it as 'a notable improvement over Grok 4.6 at the same price and speed'.\n\nThe benchmarks, however, tell a familiar story. Grok 4.7 scored 1695 on GDPval against 1735 for Anthropic's Claude Fable 5.1, and 1657 on the AA-Briefcase office-work benchmark against Fable 5.1's 1678, second place in both. On CursorBench it lands mid-pack on cost-effectiveness. Musk set expectations low before launch, saying Grok 4.7 should land 'roughly on par with' the older Claude Opus 5.0. He has sketched Grok 4.8 and 4.9 as meaningful step-ups, with Grok 5 as a possible frontier leader, but gave no dates, leaving xAI in the chasing pack as Anthropic and OpenAI set the pace.",
 "sources":["Decrypt","Unite.AI"],"source_urls":["https://decrypt.co/378824/xai-launches-grok-4-7","https://www.unite.ai/spacexai-releases-grok-4-7-for-coding-and-knowledge-work/"],"updated":TODAY
},
"xiaomi-mimo-v2-6-open-source-2026-09-22": {
 "headline":"Xiaomi open-sources MiMo-V2.6 and its RL machinery",
 "summary":"Xiaomi released open repositories for MiMo-V2.6-Pro and Flash and the reinforcement-learning code used to train them, at unchanged prices.",
 "detail":"Xiaomi released and open-sourced its MiMo-V2.6 series on Monday, publishing Hugging Face repositories for two omnimodal models plus the training environments and reinforcement-learning (RL) code used to build them. The release is a notably transparent move in a frontier-model race defined by careful secrecy, according to RuntimeWire's coverage of Xiaomi's launch.\n\nThe two models, MiMo-V2.6-Pro and MiMo-V2.6-Flash, both accept text, image, video and audio, and both carry a claimed 1-million-token context window. The Pro model is a sparse mixture-of-experts architecture with 1.02 trillion total parameters (42 billion active per token), while Flash lists 309 billion total (15 billion active). Xiaomi says Pro and Flash each completed 30 RL steps across roughly 750,000 trajectories in under six days of production compute.\n\nBeyond the weights, the package includes a technical report, deployment instructions and the RL system itself so third parties can reproduce the work. Xiaomi is also rolling out MiMo-V2.6-Pro-UltraSpeed, a hosted tier said to generate output up to 20 times faster than standard Pro at the same model quality. API prices are unchanged from MiMo-V2.5, and the models are listed on OpenRouter, making the open release immediately accessible to developers and a direct challenge to Western labs on cost and openness.",
 "sources":["RuntimeWire"],"source_urls":["https://runtimewire.com/article/xiaomi-open-sources-mimo-v2-6-rl-cost-3-47m"],"updated":TODAY
},
"iran-trump-threats-strikes-resume-2026-09-22": {
 "headline":"Trump threatens to wipe out Iran as the US weighs resuming strikes",
 "summary":"Trump offered to 'wipe out' Iran, let its economy 'rot' or make a deal; Iran warns of 'painful' retaliation and a tanker was hit at Hormuz.",
 "detail":"The Iran war entered a volatile new phase as Iranian leaders headed to New York for the UN General Assembly. In a Fox News interview on Sunday, President Trump said he was in 'deciding mode', listing three options, 'wiping Iran out', letting its economy 'rot', or making a deal, and later mused about when he might need to 'blow the entire nation up'. The Independent reported the remarks came as Iran's Revolutionary Guard threatened to 'change the geography of the war' and bring in new weapons if Washington escalates.\n\nIran's central military command, the Khatam al-Anbia headquarters, said intelligence shows the US is preparing to resume strikes, and warned of sustained retaliation against US bases and interests across the Middle East, declaring any regional state that supports American attacks would be treated as a party to the conflict. Tehran's conditions for renewed talks, passed through Qatari and Pakistani mediators, include ending the war, releasing frozen funds and lifting the US naval blockade.\n\nThe military escalation is playing out against a backdrop of constrained shipping. The UK Maritime Trade Operations Center reported a tanker was struck by an 'unknown projectile' as it entered the Strait of Hormuz on Monday, injuring two crew. Al Jazeera noted only 12 commodity vessels crossed the strait over the weekend, down from 35 the prior weekend, evidence that the wartime squeeze on one of the world's most critical energy chokepoints remains severe even as some tankers again transit it, and with it the war's outsized inflationary and economic stakes.",
 "sources":["Al Jazeera","CNBC","The Independent","Philadelphia Inquirer"],"source_urls":["https://www.aljazeera.com/news/2026/9/21/irans-military-says-us-preparing-to-resume-strikes","https://www.cnbc.com/2026/09/21/us-iran-war-trump-hormuz.html","https://www.independent.co.uk/news/world/middle-east/iran-us-war-live-trump-strikes-update-oil-houthis-riyadh-b3053306.html","https://www.inquirer.com/news/nation-world/iran-us-war-revolutionary-guard-warning-escalation-change-tactics-weapons-targets-tanker-struck-houthis-saudis-israel-yom-kippu-20260921.html"],"updated":TODAY
},
"russia-occupied-vote-criticised-2026-09-22": {
 "headline":"Western allies condemn Russia's Duma votes in occupied Ukraine",
 "summary":"Australia, Canada, New Zealand and Norway joined Britain in criticising Russian parliamentary elections in Ukraine's occupied regions.",
 "detail":"A widening group of Western allies lined up to condemn Russian parliamentary elections held in Ukraine's occupied territories. Sky News reported that Australia, Canada, New Zealand and Norway joined Britain in criticising the State Duma votes held in Crimea, Donetsk, Kherson, Luhansk and Zaporizhzhia, which Moscow organised as part of its legislative election. Kyiv and its partners regard any ballot in the occupied regions as an illegitimate attempt to legitimise the annexation.\n\nThe criticism extends a pattern seen since Russia's full-scale invasion: Western capitals refuse to recognise elections staged to cement control over seized territory, and the latest round reinforces that stance as the war grinds on with no settlement in sight. It comes amid continued cross-border strikes and the broader energy and economic pressures that the wartime blockade is exerting.\n\nThe exchanges landed alongside a separate development on the energy front. Sky also noted that Ukrainian President Volodymyr Zelenskyy responded publicly to a Trump social-media post about Russia 'losing control of diesel oil', a reference to Ukraine's long-range strikes on Russian refineries and fuel infrastructure, which Kyiv defends as targeting the economic base that funds the war. The clash over refinery strikes and the illegitimacy of the occupied-territory polls together illustrate how both the battlefield and the diplomatic front remain contested.",
 "sources":["Sky News"],"source_urls":["https://news.sky.com/story/ukraine-war-latest-putin-russia-aviation-threat-12541713"],"updated":TODAY
},
"mars-jezero-water-systems-2026-09-22": {
 "headline":"NASA finds Mars' Jezero 'Margin Unit' was shaped by lakes and hydrothermal fluids",
 "summary":"Perseverance-rover analysis reveals Jezero Crater's Margin Unit was reshaped by ancient lakes, groundwater and hydrothermal systems over three wet episodes.",
 "detail":"A new NASA-led study has untangled the geological history of Jezero Crater's enigmatic 'Margin Unit', the same location the Perseverance rover's cache was chosen around. The research, published Monday in Communications Earth & Environment, shows the feature was shaped by a complex sequence of ancient lakes, groundwater systems and hydrothermal fluids, according to a NASA Jet Propulsion Laboratory release.\n\nThe Martian rover had originally been expected to find lake or river sediments at the margin, but instead the team encountered igneous rock, the kind that forms from magma deep underground or volcanic activity at the surface. Igneous rocks are excellent record-keepers because the mineral crystals within them preserve details of the precise moment they formed, and in this case they preserved an unusually detailed record of water activity on early Mars.\n\nThe findings show the rocks interacted with water on at least three separate occasions, each encounter further altering their chemistry and appearance. That sequence points to a dynamic early Mars with a long-lived, evolving water history at Jezero, a site that famously hosted an ancient lake and river delta. Beyond reconstructing the crater's past, the work helps scientists understand where and when habitable environments may have existed, and sharpens the context for the samples the rover is collecting for future return to Earth.",
 "sources":["NASA JPL"],"source_urls":["https://www.jpl.nasa.gov/news/nasa-discovery-reveals-complex-water-systems-on-early-mars/"],"updated":TODAY
},
"youngest-exoplanet-2026-09-22": {
 "headline":"Elias 2-24 b confirmed as the youngest planet ever found, still growing",
 "summary":"Digging through Keck archive data, astronomers confirmed Elias 2-24 b as the youngest known exoplanet, a giant still forming far from its star.",
 "detail":"Astronomers have confirmed Elias 2-24 b as the youngest planet ever recorded, a title that previously belonged to planets roughly five times older. The discovery, reported by Earth.com, was made not by pointing a telescope at a new target but by re-analysing old observations pulled from the W. M. Keck Observatory archive, a joint project with the NASA Exoplanet Science Institute at Caltech/IPAC.\n\nThe planet lies 55 times farther from its star than Earth is from the Sun, and it is still growing within the dusty disk swirling around its young host. A team led by Andrea Bernardi, a doctoral candidate at Chile's Universidad Diego Portales, found the same faint point of light in Keck observations from 2018 and 2020, then tracked how it moved over time, confirming it behaves like a real planet rather than a glitch or background star.\n\nThe find solves a puzzle that had sat unsolved for about a decade. Instruments had already noticed a gap in the young star's dusty disk, a ring-shaped clearing that planet-formation theory struggles to explain appearing so early and so far out, plus a faint point of light inside it. Standard models suggest a Jupiter-sized planet takes about five million years to form at Jupiter's distance, and longer farther out, yet this object already looked planetary. The confirmation of Elias 2-24 b as the youngest known planet provides the first observational anchor for how giant planets assemble, and Bernardi's team noted that NASA's recently launched Roman Space Telescope, with its sharper coronagraph, should make such infant-planet detections far more routine.",
 "sources":["Earth.com"],"source_urls":["https://www.earth.com/space/youngest-planet-ever-found-is-still-growing-around-its-star/"],"updated":TODAY
},
"oil-fourth-day-slide-2026-09-22": {
 "headline":"Oil slides for a fourth day as Saudi supply fears ease",
 "summary":"Brent fell 3.4% to $100.34 and WTI 4.5% to $95.78 on Monday, their lowest closes since Sept 8, on easing supply fears.",
 "detail":"Oil prices fell for a fourth consecutive session on Monday, with Brent settling 3.4% lower at $100.34 a barrel and West Texas Intermediate dropping 4.5% to $95.78, the lowest closes for both benchmarks since September 8, according to MarketWatch. The slide eased immediate supply concerns tied to the Iran conflict, as traders weighed prospects for a partial recovery in Gulf shipments and some tankers again using the Strait of Hormuz.\n\nThe pullback marks a meaningful retreat from the spike that pushed Brent above $100 and toward the $108 peaks seen in recent weeks, driven by the closure of Saudi Arabia's East-West pipeline and heavy disruption to Hormuz traffic. Monday's move brought some relief to markets that had braced for sustained triple-digit crude, and it came alongside hopes for a rebound in Saudi oil flows.\n\nThe reprieve is widely seen as fragile. CNBC reported analysts at Eurasia Group forecasting Brent to trade in a $90-110 band through the rest of the year, arguing that even a recovery in oil flows would not be enough to address the overall market deficit. Iran's threats to keep a chokehold on shipping through proxies and tanker attacks, and the strike on a tanker entering Hormuz on Monday, mean the supply risk premium behind the rally has not gone away, only ebbed. For households and central banks already wrestling with an inflation scare, the question is whether this slide is a genuine turning point or just a pause before the next escalation.",
 "sources":["MarketWatch","Business Insider","CNBC"],"source_urls":["https://www.marketwatch.com/story/oil-prices-fall-for-fourth-day-as-supply-concerns-ease-2nd-update-0be75bfa","https://www.businessinsider.com/oil-prices-today-brent-crude-wti-iran-war-diplomacy-2026-9","https://www.cnbc.com/2026/09/21/us-iran-war-trump-hormuz.html"],"updated":TODAY
}
}

deep.setdefault("deepdives", {})
deep["deepdives"][TODAY] = dd
with open('/home/rory/Projects/news-pwa/deepdives.json','w') as f:
    json.dump(deep, f, ensure_ascii=False, indent=2)

ok = all(len(e.get("detail",""))>300 for e in dd.values())
missing = [k for k,v in dd.items() if len(v.get("detail",""))<=300]
print("DEEP today entries:", len(dd), "| all detail>300:", ok, "| missing:", missing)